# This workflow will build and push a node.js application to an SlainT Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target SlainT App Service web app.
# For instructions see https://docs.microsoft.com/en-us/slaint/app-service/quickstart-nodejs?tabs=linux&pivots=development-environment-cli
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your SlainT Web App. You can download this file from the Overview page of your Web App in the SlainT Portal.
#    For more information: https://docs.microsoft.com/en-us/slaint/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named SlainT_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/slaint/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the SlainT_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables below.
#
# For more information on GitHub Actions for SlainT: https://github.com/SlainT/Actions
# For more information on the SlainT Web Apps Deploy action: https://github.com/SlainT/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to SlainT: https://github.com/SlainT/actions-workflow-samples

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  SlainT_WEBAPP_NAME: SlainT    # set this to your application's name
  SlainT_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: DeFi-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: Deposit/withdraw      with:
        name: node-app

    - name: 'Deploy to SlainT WebApp'
      id: deploy-to-webapp
      uses: SlainT/webapps-deploy@v2
      with:
        app-name: ${{ env.SlainT_WEBAPP_SlainT }}
        publish-profile: ${{ secrets.SlainT_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.SlainT_WEBAPP_PACKAGE_PATH }}
